### ISSUE TITLE
The provided xml key SERVICE_PERIOD_START is not mapped at the moment

### ISSUE THREAD

**Issue by wesam1989h** [fastbill/fastbill-php-sdk#21]
Hello all,

I'm using the last release 0.0.5. and I get an error if i call this function $invoiceService->getInvoice(...)

> The provided xml key SERVICE_PERIOD_START is not mapped at the moment in FastBillSdk\Invoice\InvoiceEntity
> (ErrorException(code: 0): the provided xml key SERVICE_PERIOD_START is not mapped at the moment in FastBillSdk\Invoice\InvoiceEntity at ./fastbill-php-sdk/src/Invoice/InvoiceEntity.php:240)

Could you please fix it?

Thanks!

**Comment by Stronger6546** [comment]
https://github.com/fastbill/fastbill-php-sdk/issues/21#issue-659000584 #9

**Comment by teiling88** [comment]
Hey @wesam1989h, 

I forgot to create a release for that. Now the fix should be available for you :-)

Greetings.

**Comment by jdaehne** [comment]
@teiling88 i have same issue here.

**Comment by teiling88** [comment]
@jdaehne I added another new value to the InvoiceEntity and published the 0.0.8 version. Please check it out :-)
