### ISSUE TITLE
Creating ItemEntity with unitPrice of 0 (zero)

### ISSUE THREAD

**Issue by jdaehne** [fastbill/fastbill-php-sdk#33]
I try to setup an invoice with some free products. It is not possible to add an item with the unitPrice set to 0.

Would it be possible to change this like it is done in this issue: https://github.com/fastbill/fastbill-php-sdk/issues/29

That would be so great.

Thanks a lot.

**Comment by jdaehne** [comment]
@teiling88 Thanx a lot for fixing this issue. But it is still not working. I think the problem is the fastbill API endpoint that does not let me add free products. Is there any chance to get the API fixed too? Because inside the fastbill UI i can create free products. But if i try to do the same via API i get a bad response.

**Comment by teiling88** [comment]
@Roritharr can you have a look into it, please? :-)

**Comment by jdaehne** [comment]
@teiling88 @Roritharr i just would like to check back on this: Is there any chance to get this working? :-)

**Comment by teiling88** [comment]
Hey @jdaehne,
I'm not working for fastbill anymore. So I can only fix SDK related things. Maybe you create a ticket via support@? 
Greetings,
Thomas

**Comment by rmaudrich** [comment]
Hi @jdaehne, we at FastBill will look into this right now.

**Comment by rmaudrich** [comment]
@jdaehne - can you specify what you tried to send to our API and what result came back?

**Comment by jdaehne** [comment]
@rmaudrich i try to create a product in an invoice with the unitPrice of 0. The scenario is for example that we have hosting-products that already include one free domain. That domain must bee listet in the invoice with a price of 0. That does not work. I have to set the price greater then 0.

Here is the code example: 

```
// create invoice object
$invoiceEntity = new InvoiceEntity();
$invoiceEntity->customerId = $invoice['customer'];
$invoiceEntity->invoiceTitle = 'Hosting-Rechnung';

// add items to invoice
foreach ($invoice['items'] as $item) {
    $invoiceItem = new ItemEntity();
    $invoiceItem->description = $this->formattingDescription($item);
    $invoiceItem->unitPrice = ($item['price'] <= 0) ? (int) 0 : $item['price'];
    $invoiceItem->quantity = 12;
    $invoiceItem->vatPercent = $this->getTaxRateforCustomer($invoice['customer']);
    $invoiceEntity->items[] = $invoiceItem;
}

// create invoice
$result = $this->invoiceService->createInvoice($invoiceEntity);

if (!$result->invoiceId) {
    $this->warn('Invoice could not be created. Client: ' . $invoice['customer']);
    return false;
}
```

At the moment i get an "429 Too Many Requests" message. So i will check this in an hour again and send you the exact result message.

**Comment by pclauberg** [comment]
Hi @jdaehne, Peter from FastBill here.

I checked our logs, and it seems that the API-call in question is missing the unitPrice completely and therefore you got the error in the response.

The call was sent to us today at 13:23:15. Did you omit the unitPrice from your call?
The field UNIT_PRICE is a required field in the ITEMS-section. It may be empty, but it needs to be submitted.

**Comment by teiling88** [comment]
You are welcome!
