### ISSUE TITLE
Add RecurringCreate

### ISSUE THREAD

**Issue by pclauberg** [fastbill/fastbill-php-sdk#36]
The RecurringInvoiceEntity.php already exists, but the repo is missing the necessary files to create a recurring invoice, like for invoices or estimates.

**Comment by teiling88** [comment]
Hey @pclauberg, 
yes I will fix that next week! 

Greetings.
Thomas

**Comment by teiling88** [comment]
Hey @pclauberg,
I have no idea where I can find the recurring invoices in fastbill but it should work if I interpret the responses correctly :-) 
So I released the new sdk Version 0.1.0. Let me know if something is left over or everything is fine! 
Greetings

**Comment by pclauberg** [comment]
Hi @teiling88,
you find the recurring invoices through our invoices list.
I add the FAQ-article for reference.
https://support.fastbill.com/hc/en-us/articles/201715197-How-to-administrate-your-recurring-invoices
I can check the fix tomorrow and report back.
Greetings

**Comment by teiling88** [comment]
Hey @pclauberg,

ok than it works :-)

Greetings,
Thomas
