### ISSUE TITLE
InvoiceSearchStruct()->setStartDueDate() expects \DateTime but fails.

### ISSUE THREAD

**Issue by chluehr** [fastbill/fastbill-php-sdk#4]
Sample Code:

`$invoiceSearchStruct = new InvoiceSearchStruct();
$invoiceSearchStruct->setStartDueDate(new \DateTime('2018-12-01'));`

Results in Error:

> In XmlService.php line 85:
> Catchable Fatal Error: Object of class DateTime could not be converted to string

Using Carbon it works:

`$invoiceSearchStruct = new InvoiceSearchStruct();
$invoiceSearchStruct->setStartDueDate(new Carbon('2018-12-01'));`

**Comment by teiling88** [comment]
Oh good catch - the type hinting was not correct. At the moment I need directly the correct Date value as a string. I fixed it for the moment with this [commit](https://github.com/fastbill/fastbill-php-sdk/commit/da5d3409796d069f58f086d3dbc6645b9580b58c)
