### ISSUE TITLE
$invoiceService->getInvoice( ..) -> XML Key COMMENTS is not mapped

### ISSUE THREAD

**Issue by chluehr** [fastbill/fastbill-php-sdk#5]
In InvoiceEntity.php line 237:

>   User Notice: the provided xml key COMMENTS is not mapped at the moment in FastBillSdk\Invoice\InvoiceEntit

**Comment by teiling88** [comment]
Hard to find this bug. The Documentation seems to be incomplete there. I fixed the issue with: https://github.com/fastbill/fastbill-php-sdk/commit/b2cb50941b41141db9a3ca82364c1b4cc538c7c6

**Comment by christophluehr** [comment]
Seems to work!

**Comment by teiling88** [comment]
Thank you for your feedback!
