### ISSUE TITLE
Invoice paymentType

### ISSUE THREAD

**Issue by jdaehne** [fastbill/fastbill-php-sdk#50]
Hi,

i try to set the "payment Type" for an invoice to "Lastschrtift = 2". But it does not have any affects. I was expecting to see the SEPA Text on the invoice. Instead the regular text is still showing. Is there a way to set the text for the payment for an invoice?

I thought this would change the default Text on the invoice to SEPA text:
`$invoiceEntity->paymentType = 2;`

Best regards
Jan

**Comment by teiling88** [comment]
Hey jdaehne,
in the documentation is this field not listet for the creation process (https://apidocs.fastbill.com/fastbill/en/invoice.html#invoice.create). 
Has the customer the flag set "Zahlungshinweis: Hinweis auf der Rechnung anzeigen"? and billingtype is set to sepa?
If this flag is activated, I see the text on the invoice.

**Comment by jdaehne** [comment]
Hi @teiling88 ,
thanx for checking this. I know the process of setting the flags for the customer globally. But i was hoping there is a way to do this individually on every invoice. Because some clients would like to pay recuring invoices via "SEPA" and other "bigger" invoices via "Rechnung". Thanx a lot. I will try my luck with the fastbill support. :-)
