### ISSUE TITLE
Entity encoding / XML

### ISSUE THREAD

**Issue by chluehr** [fastbill/fastbill-php-sdk#9]
Case:

1. search for an entity (invoice, estimate ...)
1. save the entity again

This fails, if any html specialchars are present (e.g. & in the title), because they are decoded on retrieval into the DAO and NOT encoded during xml request generation.

yes, i will try to do a pull request .... :)

**Comment by teiling88** [comment]
> yes, i will try to do a pull request .... :)

Sounds perfect :-)

**Comment by teiling88** [comment]
Hey @chluehr,

I created a pull request for this issue: https://github.com/fastbill/fastbill-php-sdk/pull/15 

Can you please check, if this solves your issue?

Thanks!

**Comment by teiling88** [comment]
Hey @chluehr, 
I will close this issue because I think the PR fixes your issue. If something else doesn't work as expected fell free to create a new issue. 
Thanks!

**Comment by chluehr** [comment]
Sorry, thanks - i guess so. Haven't had the time to work on this, yet.
Appreciate your efforts!

Kindest regards, Chris

Thomas Eiling <notifications@github.com> schrieb am So., 10. Nov. 2019,
22:35:
